### ISSUE TITLE
text_classification.ipynb not yet run

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#10]
Due to https://github.com/gradient-ai/Graphcore-HuggingFace/issues/1 .

**Comment by zzweig** [comment]
@zzweig to confirm that you can login. If we can do it great. If not then we will comment out the cell.

**Comment by nmb-paperspace** [comment]
The notebook will not produce meaningful results without the login: all cells after the login cell require that cell to have run. I can look after getting some of the higher priority content final details ready for launch.

**Comment by internetoftim** [comment]
The problem was due to incompatible transformers version. Added cell to fix installation to` pip install transformers==4.20.0`

**Comment by nmb-paperspace** [comment]
Ah so it's the same problem HF Optimum had, with the requirements saying transformers >= 4.18.0 so it picks up 4.21 not 4.20, but manifesting differently here as a login failure instead of nan loss. Thanks for fixing!
