### ISSUE TITLE
Remove `Other Examples` folder

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#11]
Great to show, but we don't have time to test them before the Aug 10th launch so it is better to hide them for now than present them untested and without modified text so that they make sense on a Paperspace setup. Especially because they are mostly `.py` and not `.ipynb`. We can potentially test+add them after the launch.

**Comment by zzweig** [comment]
@internetoftim will remove this folder until they are fully tested.
