### ISSUE TITLE
HF Optimum notebook not using cached model

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#20]
The symbolic link says no such file or directory
![Screen Shot 2022-08-10 at 6 03 45 PM](https://user-images.githubusercontent.com/74800360/184064184-6f85eb9c-b04f-48e9-97ce-29b04d296559.png)

**Comment by internetoftim** [comment]
THe `/tmp/exe_cache` is the wrong folder (will send a PR)

**Comment by nmb-paperspace** [comment]
Tested this, now compiles quickly
