### ISSUE TITLE
simple_test_data is not defined

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#40]
In `useful-tips/managing_ipu_resources.ipynb`, 2 cells with

```
sentiment_pipeline(simple_test_data)
```

fail because `simple_test_data` is not defined.

If it's set to be `["IPUs are great!", "Notebooks are easy to program in"]`, as in an earlier cell, this fixes.

(Note leaving this for Graphcore side to fix so can propagate back to original repos.)

**Comment by rahult-graphcore** [comment]
This has been fixed: https://github.com/gradient-ai/Graphcore-HuggingFace/commit/f14a2de1dd71a21114d63360e5cdc625f9f921de
