### ISSUE TITLE
Audio processing folder link in README_first gives GitHub 404

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#45]
The link in "The audio-processing folder contains notebooks for automatic speech recognition" in `README_first.ipynb` links to audio_processing.ipynb, which was taken out and so is now 404.

**Comment by rahult-graphcore** [comment]
This has been fixed in our Graphcore-internal repository, and will be pushed in our next update with the 3.1 sdk
https://github.com/graphcore/Graphcore-HuggingFace-fork/blob/prepare-sdk-release-3.1/README_first.ipynb

**Comment by rahult-graphcore** [comment]
The link has been updated to point at the `audio_classification.ipynb` notebook. However, Paperspace doesn't seem to support opening notebooks via these links, so it tries to download the notebook file instead.

**Comment by rahult-graphcore** [comment]
We've just removed the audio_classification notebook, as explained in #54 , so now the link in README_first points to the wav2vec2 fine-tuning notebook instead. I think we can close this issue?

**Comment by nmb-paperspace** [comment]
Yes, OK to close. Thanks for updating.
