### ISSUE TITLE
AutoFeatureExtractor cell fails with EuroSAT is not a local folder

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#47]
In `image_classification.ipynb`, the cell with `from transformers import AutoModelForImageClassification, AutoFeatureExtractor` fails with

```
OSError: username-or-organization/vit-base-patch16-224-in21k-finetuned-eurosat is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
```

This blocks the remainder of the notebook (3 cells).

**Comment by rahult-graphcore** [comment]
For this cell the user is meant to replace the `repo_name` var with their own HF username link. The markdown cell before it mentions `Simply put your Hugging Face user or organization name into the string below to load your fine-tuned model:`

**Comment by nmb-paperspace** [comment]
OK now if `repo_name` is undefined it's handled with the `except` so I'll close this
