### ISSUE TITLE
Question answering link has GitHub 404

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#48]
The Markdown cell `You can find a script version of this notebook to fine-tune your model in a distributed fashion using multiple GPUs or TPUs here` in `question_answering.ipynb` link to GitHub is a 404.

**Comment by rahult-graphcore** [comment]
We've removed this markdown cell in our internal repo, it will be pushed to the gradient repo in our next update with sdk 3.1

**Comment by nmb-paperspace** [comment]
OK
