### ISSUE TITLE
Some notebooks have run on Colab links

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#49]
Some notebooks have links to run on Colab. We should remove these as it's confusing for users.

Including:

- `natural_language_processing/external_model.ipynb`
- `natural_language_processing/language_modelling_from_scratch.ipynb`

**Comment by rahult-graphcore** [comment]
Have removed the links to colab, the fix will be included in our next update to the gradient repo for the 3.1 sdk.

**Comment by nmb-paperspace** [comment]
OK
