### ISSUE TITLE
Some notebooks have blank cells at the end

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#50]
Minor, but they look bad in otherwise high quality presentation.

Including:

- `image-classification/image_classification.ipynb`

Under `natural_language_processing/`:

- `external_model.ipynb`
- `language_modelling_from_scratch.ipynb`
- `multiple_choice.ipynb`
- `question_answering.ipynb`
- `summarization.ipynb`
- `text_classification.ipynb`
- `token_classification.ipynb`
- `translation.ipynb`

**Comment by rahult-graphcore** [comment]
This will be fixed in our next update to the gradient repo for sdk 3.1

**Comment by nmb-paperspace** [comment]
OK thanks, these are now gone
