### ISSUE TITLE
Setup instructions Slack channel link gives 404

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#51]
"Running on Paperspace" cell links to https://nvam268plw.clehbtvty.paperspacegradient.com/files/natural-language-processing/graphcorecommunity.slack.com, which gives a Jupyter 404.

I assume this is the same on all notebooks since the instructions are merged as part of the repo setup.

**Comment by rahult-graphcore** [comment]
Hi Nick, which cell(s) contains this link? I did a simple search on the repo but returned no matches, thanks.

**Comment by nmb-paperspace** [comment]
`audio-processing/wav2vec2-fine-tuning-checkpoint.ipynb` has an example, but it's generic: any time this paragraph appears (this repo or PT or TF2) the "slack channel" link is broken. I think it's prepending the notebook URL to graphcorecommunity.slack.com.

<img width="900" alt="Screen Shot 2023-01-11 at 9 55 11 AM" src="https://user-images.githubusercontent.com/74800360/211881787-a03b177c-7f5e-4c71-928f-7d6e94d32188.png">

**Comment by nmb-paperspace** [comment]
So the content of the paragraph needs fixing at source so that when it's merged into the notebooks from the auto-repo update process it's correct in all of them.
