### ISSUE TITLE
Test notebooks on free account

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#8]
To check for any issues users on this will see

**Comment by nmb-paperspace** [comment]
Blocked by #1

**Comment by nmb-paperspace** [comment]
ViT and BERT-L OK.

**Comment by zzweig** [comment]
Testing notebooks on free accounts looks good for initial run throughs.

**Comment by nmb-paperspace** [comment]
text_classification.ipynb has not been run (#1), therefore has not been tested on a free account.

If we remove text_classification.ipynb, or run it through with the required HF login (#10), then this is complete.
